apiVersion: v1
kind: Service
metadata:
  name: c1-app-uploader
  labels:
    app: c1-app-uploader
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: c1-app-uploader
    targetPort: 80
  selector:
    app: c1-app-uploader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: c1-app-uploader
  name: c1-app-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c1-app-uploader
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: c1-app-uploader
    spec:
      containers:
      - name: c1-app-uploader
        image: $K8S_REGISTRY/c1-app-uploader:latest
        imagePullPolicy: Always
        env:
        - name: TREND_AP_KEY
          value: $UPLOADER_KEY
        - name: TREND_AP_SECRET
          value: $UPLOADER_SECRET
        - name: TREND_AP_HELLO_URL
          value: "https://agents.de-1.application.cloudone.trendmicro.com/"
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
